/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
  safelist: [
    'w-1/5',
    'w-2/5',
    'w-3/5',
    'w-4/5',
    'w-1/4',
    'w-1/2',
    'w-3/4',
    'w-full',
    'w-1/6',
    'w-2/6',
    'w-4/6',
    'w-5/6',
    'w-1/3',
    'w-2/3',
    'w-1/7',
    'w-2/7',
    'w-3/7',
    'w-4/7',
    'w-5/7',
    'w-6/7',
    
    'lg:w-1/5',
    'lg:w-2/5',
    'lg:w-3/5',
    'lg:w-4/5',
    'lg:w-1/4',
    'lg:w-1/2',
    'lg:w-3/4',
    'lg:w-full',
    'lg:w-1/6',
    'lg:w-2/6',
    'lg:w-4/6',
    'lg:w-5/6',
    'lg:w-1/3',
    'lg:w-2/3',
    'lg:w-1/7',
    'lg:w-2/7',
    'lg:w-3/7',
    'lg:w-4/7',
    'lg:w-5/7',
    'lg:w-6/7',
  ]
}
